site_name: Gurlon Docs

nav:
  - Home: index.md
  - Usage:
    - Export Data from DynamoDB: usage/export.md
    - Download Data: usage/download.md
    - Transform Data: usage/transform.md

theme:
  name: material
  icon:
    logo: fontawesome/solid/shield-dog
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.expand
    - navigation.path
    - navigation.top
    - toc.follow
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

plugins:
  - search
  - glightbox:
      auto_caption: true

markdown_extensions:
  - pymdownx.superfences
  - admonition
  - attr_list
  - md_in_html
  - tables
  - pymdownx.highlight:
      anchor_linenums: true
      use_pygments: true
      pygments_lang_class: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      permalink: True
  - pymdownx.tabbed:
      alternate_style: true
