name: CI Lint Checks

on:
    push:
      branches: [ "*" ]
    pull_request:
      branches: [ "*" ]

jobs:
  ruff-checks:
    name: ruff
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Install uv
        uses: astral-sh/setup-uv@38f3f104447c67c051c4a08e39b64a148898af3a # v4
        with:
          version: "0.5.6"
          enable-cache: true

      - name: "Set up Python"
        uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 # v5
        with:
          python-version-file: "pyproject.toml"

      - name: Install dependencies
        run: |
            uv venv
            source .venv/bin/activate
            uv sync --frozen
      - name: Ruff linting and formatting check
        run: |
            source .venv/bin/activate
            ruff check src/gurlon tests
            ruff format --check src/gurlon tests

  mypy:
    name: mypy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Install uv
        uses: astral-sh/setup-uv@38f3f104447c67c051c4a08e39b64a148898af3a # v4
        with:
          version: "0.5.6"
          enable-cache: true

      - name: "Set up Python"
        uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 # v5
        with:
          python-version-file: "pyproject.toml"

      - name: Install dependencies
        run: |
            uv venv
            source .venv/bin/activate
            uv sync --frozen
      - name: mypy static type checker
        run: |
            source .venv/bin/activate
            mypy src/gurlon
